package yggdrasil: json5;

world host {
    export ast;
}

interface ast {
    use peg: core/types.{parse-error};
    use peg: core/cst.{syntax-node, syntax-rule, text-range};

    /// Token type of the language
    enum json5-token {
        %value,
        %object,
        %object-pair,
        %object-key,
        %array,
        %string,
        %double-string-element,
        %single-string-element,
        %hex-escape,
        %any-escape,
        %double-string-text,
        %single-string-text,
        %number,
        %boolean,
        %null,
        %identifier,
        %colon,
        %comma,
        %comment,
        %white-space,
        %string0,
        %string1,
        %boolean0,
        %boolean1,
        %hidden-text,
    }

    variant json5-type {
        %value(json5-value-node),
        %object(json5-object-node),
        %object-pair(json5-object-pair-node),
        %object-key(json5-object-key-node),
        %array(json5-array-node),
        %string(json5-string-node),
        %double-string-element(json5-double-string-element-node),
        %single-string-element(json5-single-string-element-node),
        %hex-escape(json5-hex-escape-node),
        %any-escape(json5-any-escape-node),
        %double-string-text(json5-double-string-text-node),
        %single-string-text(json5-single-string-text-node),
        %number(json5-number-node),
        %boolean(json5-boolean-node),
        %null(json5-null-node),
        %identifier(json5-identifier-node),
        %colon(json5-colon-node),
        %comma(json5-comma-node),
        %comment(json5-comment-node),
        %white-space(json5-white-space-node),
        %string0(json5-string0-node),
        %string1(json5-string1-node),
        %boolean0(json5-boolean0-node),
        %boolean1(json5-boolean1-node),
    }
    parse-string: func(text: string, offset: u32, rule: json5-token) -> result<json5-type, parse-error>;
    // AST Types
    variant json5-value-node {
        %object(json5-object-node),
        %array(json5-array-node),
        %string(json5-string-node),
        %number(json5-number-node),
        %boolean(json5-boolean-node),
        %null(json5-null-node),
    }
    // AST Types
    variant json5-object-key-node {
        %identifier(json5-identifier-node),
        %string(json5-string-node),
    }
    // AST Types
    variant json5-string-node {
        %string0(json5-string0-node),
        %string1(json5-string1-node),
    }
    // AST Types
    variant json5-double-string-element-node {
        %hex-escape(json5-hex-escape-node),
        %any-escape(json5-any-escape-node),
        %double-string-text(json5-double-string-text-node),
    }
    // AST Types
    variant json5-single-string-element-node {
        %hex-escape(json5-hex-escape-node),
        %any-escape(json5-any-escape-node),
        %single-string-text(json5-single-string-text-node),
    }
    // AST Types
    variant json5-boolean-node {
        %true(json5-boolean0-node),
        %false(json5-boolean1-node),
    }
    resource json5-object-node {
        ctor: static func(super: syntax-node) -> result<json5-object-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-object-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-object-pair-node {
        ctor: static func(super: syntax-node) -> result<json5-object-pair-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-object-pair-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-array-node {
        ctor: static func(super: syntax-node) -> result<json5-array-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-array-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-hex-escape-node {
        ctor: static func(super: syntax-node) -> result<json5-hex-escape-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-hex-escape-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-any-escape-node {
        ctor: static func(super: syntax-node) -> result<json5-any-escape-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-any-escape-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-double-string-text-node {
        ctor: static func(super: syntax-node) -> result<json5-double-string-text-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-double-string-text-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-single-string-text-node {
        ctor: static func(super: syntax-node) -> result<json5-single-string-text-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-single-string-text-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-number-node {
        ctor: static func(super: syntax-node) -> result<json5-number-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-number-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-null-node {
        ctor: static func(super: syntax-node) -> result<json5-null-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-null-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-identifier-node {
        ctor: static func(super: syntax-node) -> result<json5-identifier-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-identifier-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-colon-node {
        ctor: static func(super: syntax-node) -> result<json5-colon-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-colon-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-comma-node {
        ctor: static func(super: syntax-node) -> result<json5-comma-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-comma-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-comment-node {
        ctor: static func(super: syntax-node) -> result<json5-comment-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-comment-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-white-space-node {
        ctor: static func(super: syntax-node) -> result<json5-white-space-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-white-space-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-string0-node {
        ctor: static func(super: syntax-node) -> result<json5-string0-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-string0-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-string1-node {
        ctor: static func(super: syntax-node) -> result<json5-string1-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-string1-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-boolean0-node {
        ctor: static func(super: syntax-node) -> result<json5-boolean0-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-boolean0-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
    resource json5-boolean1-node {
        ctor: static func(super: syntax-node) -> result<json5-boolean1-node, parse-error>;
        parse-string: static func(text: string, offset: u32) -> result<json5-boolean1-node, parse-error>;
        get-rule: func() -> syntax-rule;
        get-string: func() -> string;
        get-range: func() -> text-range;
    }
}

interface visitor {

}

interface listener {

}