package yggdrasil: json;

world host {
  import peg: core/types;
  export ast;
}

interface ast {
  use peg: core/errors.{parse-error};
  use peg: core/cst.{syntax-node};

  /// Token type of the language
  enum json-token {
    json,
    json-number,
    json-string,
    json-array
  }

  variant json-type {
    json(json-node),
    json-number(json-number-node),
    json-string(json-string-node),
  }

  // AST Types
  variant json-node {
    number(json-number-node),
    str(json-string-node),
    array(json-array-node)
  }

  resource json-number-node {

  }
  resource json-string-node {

  }

  resource json-array-node {
    ctor: static func(super: syntax-node) -> result<json-array-node, parse-error>;
    //     get-super: func() -> syntax-node;
    parse-string: static func(text: string, offset: u32) -> result<json-array-node, parse-error>;
    get-text: func() -> string;
    item: func() -> list<json-node>;
  }
}

interface visitor {

}

interface listener {

}
