[package]
name = "json5-parser"
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "Command line build example"
homepage = "https://github.com/ygg-lang/yggdrasil-rs"
repository = "https://github.com/ygg-lang/yggdrasil-template/tree/master/projects/build_by_cli"
documentation = "https://docs.rs/json5-parser"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"
exclude = ["package.json", "tests/**"]

[dependencies]
rctree = "0.6.0"
indextree = "4.6.0"
wit-bindgen = "0.22.0"
nyar-error = { version = "0.1.16", features = ["yggdrasil-rt"] }

[dependencies.yggdrasil-rt]
version = "0.1.2"
#path = 'C:\Users\Dell\CLionProjects\yggdrasil.rs\projects\ygg-rt'

#[dependencies.yggdrasil-wasi]
#version = "0.0.0"
#path = 'C:\Users\Dell\CLionProjects\yggdrasil.rs\projects\ygg-rt'

[dev-dependencies]


[features]
default = []
